name: dawid_wnukowski_2023
description: Demo of my current architecture approach.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

# There is more plugins that this demo app requires. It's on purpose to show the plugins I usually add to my projects.
dependencies:
  cupertino_icons: ^1.0.2
  dio: 5.2.1+1
  either_dart: ^1.0.0
  firebase_crashlytics: ^3.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: 2.3.6
  freezed_annotation: 2.2.0 # Sometimes I prefer to write code manually instead of generating it. It's not always slower, especially if the team members have diverse seniority levels.
  go_router: 9.0.3
  intl: 0.18.1
  json_annotation: 4.8.1
  shared_preferences: 2.2.0
  talker_dio_logger: ^2.2.0
  talker_logger: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/